-- Run this once in the Supabase SQL Editor for the MLB project.
-- Browser users can only read fully completed table snapshots.  Writes are
-- performed by GitHub Actions with SUPABASE_SECRET_KEY.

create extension if not exists pgcrypto;

create table if not exists public.mlb_scrape_runs (
    id uuid primary key default gen_random_uuid(),
    selected_date date not null,
    status text not null check (status in ('running', 'complete', 'failed')),
    games_count integer not null default 0 check (games_count >= 0),
    current_game_pk bigint,
    current_table text,
    completed_steps jsonb not null default '[]'::jsonb,
    error_message text,
    started_at timestamptz not null default now(),
    finished_at timestamptz
);

create table if not exists public.mlb_game_table_snapshots (
    id bigint generated by default as identity primary key,
    selected_date date not null,
    game_pk bigint not null,
    away_team text not null,
    home_team text not null,
    away_starter text not null default '',
    home_starter text not null default '',
    table_key text not null check (
        table_key in (
            'starterH2H',
            'starterRecent',
            'highLevH2H',
            'highLevRecent',
            'midLevH2H',
            'midLevRecent',
            'lowLevH2H',
            'lowLevRecent',
            'unplayablePitchers',
            'hittingRecent'
        )
    ),
    table_order smallint not null check (table_order between 1 and 10),
    status text not null check (status = 'complete'),
    payload jsonb not null,
    run_id uuid references public.mlb_scrape_runs(id) on delete set null,
    collected_at timestamptz not null default now(),
    unique (game_pk, table_key)
);

create index if not exists mlb_snapshots_date_game_idx
    on public.mlb_game_table_snapshots (selected_date, game_pk, table_order);

alter table public.mlb_scrape_runs enable row level security;
alter table public.mlb_game_table_snapshots enable row level security;

-- Secret keys are mapped to service_role.  RLS is bypassed for that role, but
-- explicit table/sequence grants are still required on projects using the
-- newer restrictive default privileges.
grant select, insert, update on table public.mlb_scrape_runs to service_role;
grant select, insert, update on table public.mlb_game_table_snapshots to service_role;
grant usage, select on sequence public.mlb_game_table_snapshots_id_seq to service_role;

revoke all on table public.mlb_scrape_runs from anon, authenticated;
revoke insert, update, delete on table public.mlb_game_table_snapshots
    from anon, authenticated;
grant select on table public.mlb_game_table_snapshots to anon, authenticated;

drop policy if exists "Public can read completed MLB snapshots"
    on public.mlb_game_table_snapshots;
create policy "Public can read completed MLB snapshots"
    on public.mlb_game_table_snapshots
    for select
    to anon, authenticated
    using (status = 'complete');
