-- Run this once in the Supabase SQL Editor for the MLB project.
-- Browser users can only read fully completed table snapshots.  Writes are
-- performed by GitHub Actions with SUPABASE_SECRET_KEY.

create extension if not exists pgcrypto;

create table if not exists public.mlb_scrape_runs (
    id uuid primary key default gen_random_uuid(),
    selected_date date not null,
    status text not null check (status in ('running', 'complete', 'failed')),
    games_count integer not null default 0 check (games_count >= 0),
    current_game_pk bigint,
    current_table text,
    completed_steps jsonb not null default '[]'::jsonb,
    error_message text,
    started_at timestamptz not null default now(),
    finished_at timestamptz
);

create table if not exists public.mlb_game_table_snapshots (
    id bigint generated by default as identity primary key,
    selected_date date not null,
    game_pk bigint not null,
    away_team text not null,
    home_team text not null,
    away_starter text not null default '',
    home_starter text not null default '',
    table_key text not null check (
        table_key in (
            'starterH2H',
            'starterRecent',
            'highLevH2H',
            'highLevRecent',
            'midLevH2H',
            'midLevRecent',
            'lowLevH2H',
            'lowLevRecent',
            'unplayablePitchers',
            'hittingRecent'
        )
    ),
    table_order smallint not null check (table_order between 1 and 10),
    status text not null check (status = 'complete'),
    payload jsonb not null,
    run_id uuid references public.mlb_scrape_runs(id) on delete set null,
    collected_at timestamptz not null default now(),
    unique (game_pk, table_key)
);

create table if not exists public.mlb_scrape_requests (
    id bigint generated by default as identity primary key,
    selected_date date not null unique,
    status text not null default 'pending'
        check (status in ('pending', 'running', 'complete', 'failed')),
    attempts integer not null default 0 check (attempts >= 0),
    requested_at timestamptz not null default now(),
    started_at timestamptz,
    finished_at timestamptz,
    error_message text,
    run_id uuid references public.mlb_scrape_runs(id) on delete set null
);

create index if not exists mlb_snapshots_date_game_idx
    on public.mlb_game_table_snapshots (selected_date, game_pk, table_order);

create index if not exists mlb_scrape_requests_pending_idx
    on public.mlb_scrape_requests (status, requested_at);

alter table public.mlb_scrape_runs enable row level security;
alter table public.mlb_game_table_snapshots enable row level security;
alter table public.mlb_scrape_requests enable row level security;

-- Secret keys are mapped to service_role.  RLS is bypassed for that role, but
-- explicit table/sequence grants are still required on projects using the
-- newer restrictive default privileges.
grant select, insert, update on table public.mlb_scrape_runs to service_role;
grant select, insert, update on table public.mlb_game_table_snapshots to service_role;
grant usage, select on sequence public.mlb_game_table_snapshots_id_seq to service_role;
grant select, insert, update on table public.mlb_scrape_requests to service_role;
grant usage, select on sequence public.mlb_scrape_requests_id_seq to service_role;

revoke all on table public.mlb_scrape_runs from anon, authenticated;
revoke insert, update, delete on table public.mlb_game_table_snapshots
    from anon, authenticated;
revoke all on table public.mlb_scrape_requests from anon, authenticated;
grant select on table public.mlb_game_table_snapshots to anon, authenticated;

drop policy if exists "Public can read completed MLB snapshots"
    on public.mlb_game_table_snapshots;
create policy "Public can read completed MLB snapshots"
    on public.mlb_game_table_snapshots
    for select
    to anon, authenticated
    using (status = 'complete');

-- Browser users cannot write to the queue table directly. They can only call
-- this narrowly-scoped function for a recent/past date. Duplicate dates are
-- coalesced, running requests stay running, and failed/completed dates may be
-- requested again after a short cooldown.
create or replace function public.request_mlb_scrape(p_selected_date date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    queued public.mlb_scrape_requests%rowtype;
begin
    if p_selected_date is null then
        raise exception 'selected date is required' using errcode = '22023';
    end if;
    if p_selected_date > timezone('Asia/Seoul', now())::date then
        raise exception 'future dates cannot be queued' using errcode = '22023';
    end if;
    if p_selected_date < timezone('Asia/Seoul', now())::date - 400 then
        raise exception 'dates older than 400 days cannot be queued' using errcode = '22023';
    end if;

    insert into public.mlb_scrape_requests (
        selected_date,
        status,
        requested_at,
        started_at,
        finished_at,
        error_message,
        run_id
    )
    values (
        p_selected_date,
        'pending',
        now(),
        null,
        null,
        null,
        null
    )
    on conflict (selected_date) do update
    set
        status = case
            when mlb_scrape_requests.status in ('pending', 'running')
                then mlb_scrape_requests.status
            when mlb_scrape_requests.requested_at > now() - interval '30 minutes'
                then mlb_scrape_requests.status
            else 'pending'
        end,
        requested_at = case
            when mlb_scrape_requests.status in ('pending', 'running')
                then mlb_scrape_requests.requested_at
            when mlb_scrape_requests.requested_at > now() - interval '30 minutes'
                then mlb_scrape_requests.requested_at
            else now()
        end,
        started_at = case
            when mlb_scrape_requests.status in ('pending', 'running')
                or mlb_scrape_requests.requested_at > now() - interval '30 minutes'
                then mlb_scrape_requests.started_at
            else null
        end,
        finished_at = case
            when mlb_scrape_requests.status in ('pending', 'running')
                or mlb_scrape_requests.requested_at > now() - interval '30 minutes'
                then mlb_scrape_requests.finished_at
            else null
        end,
        error_message = case
            when mlb_scrape_requests.status in ('pending', 'running')
                or mlb_scrape_requests.requested_at > now() - interval '30 minutes'
                then mlb_scrape_requests.error_message
            else null
        end,
        run_id = case
            when mlb_scrape_requests.status in ('pending', 'running')
                or mlb_scrape_requests.requested_at > now() - interval '30 minutes'
                then mlb_scrape_requests.run_id
            else null
        end
    returning * into queued;

    return jsonb_build_object(
        'selectedDate', queued.selected_date,
        'status', queued.status,
        'requestedAt', queued.requested_at
    );
end;
$$;

revoke all on function public.request_mlb_scrape(date) from public;
grant execute on function public.request_mlb_scrape(date) to anon, authenticated;
